name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.platform }}
    
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev patchelf

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Clean npm cache and dependencies
        shell: bash
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force

      - name: Install frontend dependencies
        run: npm install

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          VITE_AUTH_BASE_URL: https://lokusmd.com
        with:
          projectPath: .
          configPath: src-tauri/tauri.conf.json
          tagName: ${{ github.ref_name }}
          releaseName: 'Lokus ${{ github.ref_name }}'
          releaseBody: |
            🚀 **Lokus v1.3.0** - Major Feature Release

            ## 🎯 What's New Since v1.2.3

            ### 📊 Bases - Notion-like Database System
            The biggest feature in this release! Create dynamic databases from your notes.
            - **Table Views** - Sort, filter, and organize notes like spreadsheets
            - **Custom Properties** - Add metadata (tags, dates, numbers, URLs, etc.)
            - **Multiple Views** - Different perspectives of the same data
            - **Smart Filters** - Advanced query capabilities
            - **Auto-sync** - Real-time updates with your workspace

            ### 🔐 Authentication & Security
            - Fixed OAuth email confirmation URLs (now use lokusmd.com)
            - Improved token refresh and error handling
            - Better secure storage system integration
            - Windows compatibility improvements

            ### 🛠️ Developer Experience
            - Local cross-platform builds with Docker
            - Windows build support via cargo-xwin
            - Improved CI/CD workflows
            - Fixed Windows Tauri CLI npm dependencies

            ### 🎨 UI/UX Improvements
            - Enhanced code block rendering
            - Fixed launcher recent workspaces display
            - Better styling and visual polish
            - Improved workspace navigation

            ### 🐛 Bug Fixes
            - Fixed Cmd+W closing two tabs issue
            - Resolved workspace persistence bugs
            - Fixed theme persistence issues
            - Better WikiLink graph connections
            - Improved canvas save/load reliability

            ---

            ## 📦 Installation

            **🍎 macOS**
            - Download `Lokus_x64.app.tar.gz` or `.dmg`
            - Apple Silicon: Universal binary included

            **🪟 Windows**
            - Download `.msi` for installer
            - Or `.exe` for portable version

            **🐧 Linux**
            - Ubuntu/Debian: `.deb`
            - Fedora/RHEL: `.rpm`
            - Universal: `.AppImage`

            ---

            **Full Changelog**: https://github.com/lokus-ai/lokus/compare/v1.2.3...v1.3.0
          releaseDraft: false
          prerelease: false